### ISSUE TITLE
Less convoluted?

### ISSUE THREAD

**Issue by nls1729** [aquaherd/restart-on-hog#1]
I was just poking around and noticed you might prefer something that is actually intended to get a pid.

function _setpid() {
&nbsp;&nbsp;&nbsp;&nbsp;let [res, out] = GLib.spawn_command_line_sync('/usr/bin/pgrep -f /usr/bin/gnome-shell');
&nbsp;&nbsp;&nbsp;&nbsp;pid = parseInt(out).toString();
}

**Comment by aquaherd** [comment]
Thank you. However, I would rather not spawn a process for that matter.

**Comment by nls1729** [comment]
Close
